-- Insertar datos de prueba para documentos de transparencia
INSERT INTO transparency_documents (
  id,
  title,
  description,
  "fileName",
  "fileUrl",
  "fileSize",
  "fileType",
  category,
  year,
  "isActive",
  "isFeatured",
  "createdAt",
  "updatedAt"
) VALUES 
(
  'transparency_001',
  'Informe Anual 2023',
  'Informe completo de actividades y resultados del año 2023',
  'informe_anual_2023.pdf',
  'https://example.com/informe_anual_2023.pdf',
  2048000,
  'application/pdf',
  'INFORMES_ANUALES',
  2023,
  true,
  true,
  NOW(),
  NOW()
),
(
  'transparency_002',
  'Política de Transparencia',
  'Documento que establece los principios y políticas de transparencia de la fundación',
  'politica_transparencia.pdf',
  'https://example.com/politica_transparencia.pdf',
  1024000,
  'application/pdf',
  'CENTRO_DOCUMENTOS',
  NULL,
  true,
  false,
  NOW(),
  NOW()
),
(
  'transparency_003',
  'Auditoría Financiera 2023',
  'Informe de auditoría externa de los estados financieros del año 2023',
  'auditoria_financiera_2023.pdf',
  'https://example.com/auditoria_financiera_2023.pdf',
  3072000,
  'application/pdf',
  'RENDICION_CUENTAS',
  2023,
  true,
  true,
  NOW(),
  NOW()
),
(
  'transparency_004',
  'Aliados Estratégicos',
  'Lista de organizaciones aliadas y financiadores que apoyan nuestros proyectos',
  'aliados_estrategicos.pdf',
  'https://example.com/aliados_estrategicos.pdf',
  512000,
  'application/pdf',
  'FINANCIADORES_ALIADOS',
  NULL,
  true,
  false,
  NOW(),
  NOW()
),
(
  'transparency_005',
  'Memoria Institucional 2023',
  'Documento que resume los logros y desafíos del año 2023',
  'memoria_institucional_2023.pdf',
  'https://example.com/memoria_institucional_2023.pdf',
  1536000,
  'application/pdf',
  'INFORMES_ANUALES',
  2023,
  true,
  false,
  NOW(),
  NOW()
),
(
  'transparency_006',
  'Manual de Procedimientos',
  'Manual interno que describe los procedimientos operativos de la fundación',
  'manual_procedimientos.pdf',
  'https://example.com/manual_procedimientos.pdf',
  2560000,
  'application/pdf',
  'CENTRO_DOCUMENTOS',
  NULL,
  true,
  false,
  NOW(),
  NOW()
);
